### PR TITLE
Default fill to false on Polylines

### PR DESCRIPTION
**Pull request by bytesnz**
Currently the Polylines have a fill when not given any parameters as seen on https://korigan.github.io/Vue2Leaflet/examples > Geometry. It should default to no fill

### CODE REVIEW

**Comment by lordfuoco** [comment]
@bytesnz the fill comes from the Path mixin, and there should be se to false, can you fix the PR ?
And thank you.
Also please update the docs :)

**Comment by bytesnz** [comment]
Sorry for the delay. Have updated the mixins to follow Leaflet and have updated the mixins docs

**Comment by DonNicoJs** [comment]
@bytesnz Thank you! merging

**Comment by jarlehal** [comment]
will there be a v1.2.4 with this fix?

**Comment by DonNicoJs** [comment]
@jarlehal no a 1.2.4 but 2.0.0-beta.1  I  am going to release it in the next few min

**Pull request merged**
