### PR TITLE
updated types to match 1.2.3

### PR DESCRIPTION
**Pull request by HIMISOCOOL**
re-exporting L.
created GridLayer types.

### CODE REVIEW

**Comment by HIMISOCOOL** [comment]
@byWulf I noticed you have contributed to the types before, can you give this a check?

**Comment by lordfuoco** [comment]
@byWulf as soon as this is ready let me know and I will release it

**Comment by lordfuoco** [comment]
@HIMISOCOOL also l-icon was added, does it need types ? can I help here ?

**Comment by HIMISOCOOL** [comment]
@lordfuoco https://github.com/KoRiGaN/Vue2Leaflet/blame/master/types/index.d.ts#L455 looks like its already there!

**Pull request merged**
