### PR TITLE
Improve setCenter in LMap. Use latLng from leaflet.

### PR DESCRIPTION
**Pull request by bezany**
reduced function size, improved argument handler.

### CODE REVIEW

**Comment by DonNicoJs** [comment]
@bezany Thank you, I am going to make a new beta right now that includes this

**Comment by bezany** [comment]
@DonNicoJs Hello! Good news. I planning refactoring `setBounds` soon.

**Comment by DonNicoJs** [comment]
@bezany I am planning to release 2.0 this week, do you think we can manage to have that refactor in ?

**Comment by bezany** [comment]
@DonNicoJs I will trying done refactoring during two day.

**Pull request merged**
