### PR TITLE
fix unbind tooltip

### PR DESCRIPTION
**Pull request by anhnhoktvn**

### CODE REVIEW

**Comment by DonNicoJs** [comment]
@anhnhoktvn thank you for the pr, we should use the same approach for popups. Could you update the pr?

**Comment by anhnhoktvn** [comment]
Sure

**Comment by DonNicoJs** [comment]
@anhnhoktvn hi thanks for the update. I was checking the source code but at the moment I am far from my pc for few days. I will review the pr again next week

**Comment by bezany** [comment]
@anhnhoktvn Hello! Thanks for you PR.
But I'm confused between the new code and the already existing code in the [mixin Layer (unbindTooltip and unbindPopup)](https://github.com/KoRiGaN/Vue2Leaflet/blob/ca1ac2f8d3012c6fbc1bd8a1549204943607cd9a/src/mixins/Layer.js#L67). Look like it is same code.
Current code have any bug in this? Maybe try create unit test for control regression?

**Comment by anhnhoktvn** [comment]
@bezany yes, I found a bug while using with rotated marker.
[http://imgur.com/JLDjqDjl.png](http://imgur.com/JLDjqDjl.png)

**Comment by DonNicoJs** [comment]
@anhnhoktvn Okay now I see the issue, rotated-marker is not one of our core components and do not implement the layer mixin. @bezany what do you think ? should we fix our side or should we ask the other plugin to import our layer mixin ?

**Comment by bezany** [comment]
@DonNicoJs Interesting case. Anyway, I think need done code more safe through added checks that `this.parentContainer.unbindPopup` exists.
And I think we can do additional checks for more stable works with plugins.
Can combine both versions of the code?
Like this:
```javascript
if (this.parentContainer) {
	if (this.parentContainer.unbindPopup) {
		this.parentContainer.unbindPopup();
	} else if (this.parentContainer.mapObject
		&& this.parentContainer.mapObject.unbindPopup) {
		this.parentContainer.mapObject.unbindPopup();
	}
}
```
Not elegant, but reliable.

**Comment by anhnhoktvn** [comment]
@DonNicoJs @bezany I updated the code following @bezany 's suggestion. Does anything need to be done?

**Comment by DonNicoJs** [comment]
@anhnhoktvn no it's all good! Merging and thank you. I will do a release soon.

**Pull request merged**
