### PR TITLE
worked test for LMarker with parent LMap

### PR DESCRIPTION
**Pull request by bezany**
Help for #365 
I found solution how mocked $parent as LMap when test other maps components.
Use [parentComponent](https://vue-test-utils.vuejs.org/api/options.html#parentcomponent) not worked.
Found worked solution [here](https://github.com/vuejs/vue-test-utils/issues/560#issuecomment-461865315).

### CODE REVIEW

**Comment by DonNicoJs** [comment]
@bezany @mikeu how is it more useful? that I merge this? Or wait for mikeu ?

**Comment by mikeu** [comment]
@bezany thanks for the help. This looks like a step in the right direction, but I'm not sure if we're all the way there yet. I've only had fifteen minutes to check on this over the weekend, so maybe I've just missed something. I'll put more time into it tomorrow.

For some reason, `wrapper.html` returns `undefined`, instead of the content to be rendered. Perhaps we can get away without using this but, for example, I was writing a test for the `LZoomControl` and was planning to verify that after setting the `zoomInText` property to something other than `'+'`, the new string did appear in the display as expected.

I also haven't tested any of the other wrapper functions other than `setProps`, so it's possible this won't be the only strange behaviour.

@DonNicoJs as for how to merge this, I'm happy to get this test in #365 once we sort out any remaining issues, so it all comes as one bundle, or if you want to merge it now then I can pull the changes in from there. Whatever you think is best.

**Comment by bezany** [comment]
@mikeu I did refactoring `getWrapper`. Now it named `getWrapperWithMap`. It return component's wrapper and parent map wrapper.
See `LMarker.vue default slot text` for usage example.
`wrapper.html()` returns `undefined` because LMarker render `null` if not exists default slot. ([source code](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/components/LMarker.vue#L80)). I added default slot and wait re-render.

**Comment by DonNicoJs** [comment]
@bezany @mikeu Please let me know what is best for you :) I will wait to merge on both until I hear from you

**Comment by bezany** [comment]
@DonNicoJs I think you can merge this PR. After this @mikeu continue write unit tests.

**Comment by mikeu** [comment]
@bezany Good point about what the component render functions return... The LControlZoom I'd been working with is even worse, it just _always_ returns `null`. It's now obvious that I should have looked there much earlier in my investigations!

I previously had other approaches that gave the same functionality by having two different wrappers, one for the map and one for the component under test, but I was hoping for a single one. As I said in #365, I was ideally looking to have a single wrapper that provided all of the functionality we'd normally expect for components that could truly be mounted in isolation. I guess what this shows is that that was never going to be possible, since at least some of the components we want to test do not actually render themselves at all, but instead affect what their parent renders. Thanks for pointing that out!

@DonNicoJs I have integrated a version of @bezany's function to return two wrappers, one for the map and one for the component, into the latest addition to #365. I made the minor change of testing whether the component to be mounted already had a `created` hook, and calling it instead of simply overriding it, if so. Assuming that you are happy with the directory structure and test helpers in that PR, it probably makes the most sense for @bezany to update the LMarker tests to use the wrapper function from there (i.e. `import { getWrapperWithMap } from '@/tests/test-helpers'`) and move them into the `components` subdirectory, but otherwise use the tests that are already written here. What do you both think?

**Comment by mikeu** [comment]
Oh sorry @bezany , I didn't notice that you'd commented while I was working. Sure, @DonNicoJs if you want to merge this as @bezany suggests, then I can pull the updates into my other branch and keep going from there. That sounds good to me.

**Comment by DonNicoJs** [comment]
@mikeu I'll merge so that we keep this as clean as possible! @bezany if you want to help mikeu maybe you can collaborate on his fork? I wish I could add you both as collaborator here but I can't :(

**Pull request merged**
