### PR TITLE
Fix/tooltip performances 

### PR DESCRIPTION
**Pull request by lordfuoco**
This PR aims to avoid to have hundreds of tooltip elements in the DOM.
I also created a stress demo to test it.
It needs a thorough review / test .

(Last PR from pulilab fork)

### CODE REVIEW

**Comment by jperelli** [comment]
@lordfuoco your other pr was merged great work! I'm pinging you here so maybe you can now solve these conflicts

**Comment by lordfuoco** [comment]
@jperelli yes and also korrigan added me to the repo team :) did you gave a look at the code, its a bit sensitive part, for me it works but I would appreciate a good review.

**Comment by lordfuoco** [comment]
@jperelli so the performance problem at the moment is that the tooltip element leave the slot in the dom, one for each marker with tooltip. This after 100 or so tooltip slow down the page by a huge deal.
Also all this dom elements stay there even with the cluster plugin 

The idea of the fix is: 

- Let vue put the slot content in the dom
- Take it, clone it in memory (https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode ) and pass the clone to leaflet to instantiate the tooltip
- set ready to true so v-if will remove the slot from the dom

Now this works because of how vue optimise his work, and I tested it with several markers and seems to do fine, but I still think a bit of test is required.

**Comment by lordfuoco** [comment]
fixes #204

**Pull request merged**
