### PR TITLE
Add support for max-bounds option

### PR DESCRIPTION
**Pull request by katafrakt**
As documented [here](http://leafletjs.com/reference-1.2.0.html#map-maxbounds). I would need support for this in one of my projects.

### CODE REVIEW

**Comment by KoRiGaN** [comment]
Hi @katafrakt,

Thanks for this PR.

1. I don't understand why you update maxBounds when bounds are updated in the setBounds method. Could you explain me why?

2. As setMaxBounds is in the pattern "set" + propName the property doesn't need to be custom. So no definition of setMaxBounds is required and custom: true is not required either I think.

Micka

**Comment by katafrakt** [comment]
Things you noticed are mostly result of me being a total noob in Vue. So thanks for your comments, I'll make my code better according to them.

> I don't understand why you update maxBounds when bounds are updated in the setBounds method. Could you explain me why?

I felt that it might be a good idea to have bounds-related logic in one place (= one function). Looking at it now, I don't really know what was I thinking.

> As setMaxBounds is in the pattern "set" + propName the property doesn't need to be custom. So no definition of setMaxBounds is required and custom: true is not required either I think.

That's good to know. But what about validating params coming to `setMaxBounds` as they are validated in `setBounds`?

**Comment by simoneldevig** [comment]
@KoRiGaN - is this going to be merged in?

I could really use the setMaxBounds functionality as well :-)

**Comment by KoRiGaN** [comment]
@simoneldevig,

Yes it will be merged. I just need to find some time to do some work on Vue2Leaflet, I hope by the end of this week.

Micka

**Comment by simoneldevig** [comment]
@KoRiGaN - great :)

**Comment by KoRiGaN** [comment]
Hi @simoneldevig, @katafrakt,

This PR is now available in v0.0.60.

Micka

**Pull request merged**
