### PR TITLE
Mouse movement, particularly, needs to be debounced

### PR DESCRIPTION
**Pull request by disarticulate**
I'd debounce as much as possible, maybe segregate. But vue crashes development mode with sub ms events.

### CODE REVIEW

**Comment by KoRiGaN** [comment]
Hi @disarticulate,

Thanks for your pull request. 
This should be done in your own application. Vue2Leaflet is just a wrapper of Leaflet and I don't want to debounce event with some fixed rate.

I'm closing this request as it will modify Leaflet behaviour and limit potential usages.

Micka

**Comment by disarticulate** [comment]
How would you propose to debounce the event, as it's triggering inside your
component?

ie, Vue devtools records the event regardless of any listener I attach,
crashing devtools eventually.

**Comment by KoRiGaN** [comment]
Event handling have been simplified from v1.0.0 and nothing happens in Vue2Leaflet.

So if you do not set any event handler nothing should happens.
If you set an event handler just set an debounced one.

Micka

**Comment by disarticulate** [comment]
As I said, devtools for Vue does, and crashes.

**Comment by KoRiGaN** [comment]
Do you have an example/list of step that make devtools crash ?

It doesn't crash on my side.

**Comment by disarticulate** [comment]
Open, move mouse recording events.

L-mousemove event floods the screen.

Vue 2.5.16, Vue devtools v4.1.4

Maybe it's an upstream issue, but maybe you can consider whether you
actually need subms response as default.

On Mar 27, 2018 11:10 AM, "Mickaël" <notifications@github.com> wrote:

Do you have an example/list of step that make devtools crash ?

It doesn't crash on my side.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/KoRiGaN/Vue2Leaflet/pull/135#issuecomment-376582792>,
or mute the thread

**Comment by KoRiGaN** [comment]
Please give Vue2Leaflet v1.0.1 a try first.

I'm pretty sure it fixes your issue.

**Comment by disarticulate** [comment]
Ok.

**Pull request closed without merging**
